[package]
name = "cosmic-osd"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
i18n-embed = { version = "0.14", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.7"
libcosmic = { git = "https://github.com/pop-os/libcosmic", default-features = false, features = ["tokio", "wayland"] }
once_cell = "1.18.0"
rust-embed = "8.0.0"
serde = { version = "1.0.140", features = ["derive"] }
tokio = { version = "1.23.0", features = ["process"] }
tokio-stream = "0.1.11"
users = "0.11.0"
zbus = { version = "3.6.1", default-features = false, features = ["tokio"] }
