[package]
name = "cosmic-osd"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
futures = "0.3"
gtk4 = "0.4"
serde = { version = "1.0.140", features = ["derive"] }
zbus = "2.3.2"
